### ISSUE TITLE
[Windows][melodic] add Windows build support

### ISSUE THREAD

**Issue by seanyen** [ros-perception/vision_opencv#273]
This is an enhancement ticket for `vision_opencv`. I am using this ticket to track all the required work to bring up `vision_opencv` to be able to build & run on Windows/MSVC (which is verified in https://aka.ms/ros project). And hope the maintainers can take a look. Thanks!

- [x] (nice-have) [melodic] Fix travis CI #269 
- [x] (must-have) [Windows][melodic] remove path splash separator from 'package_dir' #267 
- [x] (must-have) add DLL import/export macros #266
- [x] (must-have) update CMakeLists.txt for Windows build environment #265

**Comment by seanyen** [comment]
@vrabaud

**Comment by mjcarroll** [comment]
I have merged all corresponding PRs, so I'm going to close this.
